[phases.setup]
nixPkgs = [
    "python311",             # Força o Python 3.11
    "pango",                 # Essencial para o WeasyPrint
    "gobject-introspection", # Essencial para o WeasyPrint
    "cairo",                 # Essencial para o WeasyPrint
    "gdk-pixbuf",            # Ajuda com imagens no PDF
    "harfbuzz",              # Renderização de fontes
    "librsvg"                # Renderização de vetores
]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[start]
cmd = "streamlit run main.py"
